### ISSUE TITLE
crate docker container restarting all the time and not accessible from grafana

### ISSUE THREAD

**Issue by HervePruvost** [N5GEH/n5geh.platform#3]
Hi guys,

Issue:
I got the docker containers up and running, but the crate container is not working properly. It keeps restarting all the time and is not accessible from grafana service (see images below):

![crate docker issue](https://user-images.githubusercontent.com/24978853/188814322-75e3661f-6f6f-4c7b-8077-f75036dce749.JPG)

![grafana-datasource-crate-issue](https://user-images.githubusercontent.com/24978853/188818318-db594d73-0e37-4fc9-a5b2-832e9bde73ad.JPG)

Looking at the docker logs for grafana, it looks the crate server is not visible or does not exist.

Tried so far:
I tried with several versions of docker and docker-compose (V1 and V2) but that the same. By too old docker versions the docker-compose file version was any not supported (currently v.3,8). I tried also decreasing the version number inside the docker-compose.yml file, but it did not help. 

My actual config:
docker version: 20.10.17, 
docker-compose: 2.6.0 
OS: Ubuntu 20.04.5 (WSL)

Do you please have a fix for the crate server ?

Thx
Hervé

**Comment by tstorek** [comment]
@HervePruvost did your carefully follow all instructions in the readme? Please, double-check the following steps: https://github.com/N5GEH/n5geh.platform#further-configuration-for-cratedb

**Comment by HervePruvost** [comment]
> @HervePruvost did your carefully follow all instructions in the readme? Please, double-check the following steps: https://github.com/N5GEH/n5geh.platform#further-configuration-for-cratedb

I followed the steps. Issuing "sysctl vm.max_map_count" still gives me "vm.max_map_count = 262144".

Looking at the crate docker logs, it looks like a problem with the file descriptors limit.
The last lines of the log say:
"
ERROR: [1] bootstrap checks failed
[1]: max file descriptors [4096] for crate process is too low, increase to at least [65536]
[2022-09-07T14:31:16,160][INFO ][o.e.n.Node               ] [Piz Duan] stopping ...
[2022-09-07T14:31:16,167][INFO ][o.e.n.Node               ] [Piz Duan] stopped
[2022-09-07T14:31:16,167][INFO ][o.e.n.Node               ] [Piz Duan] closing ...
[2022-09-07T14:31:16,171][INFO ][o.e.n.Node               ] [Piz Duan] closed
"

**Comment by StWiemann** [comment]
Hi @HervePruvost could you please check your systems ulimits? 
To me it sounds like your "maximum open files" ist set too low. To check your ulimits just type `ulimit -Sa`.
For open files specifically use: 
`ulimit -Sn` and `ulimit -Hn`

You might have to increase your ulimits if n is below 65536.

EDIT: It was just brought to my attention that ulimits might differ inside of a container. So please check these inside of the container as well. 
In case you need to adjust your ulimits this might be helpful: 
[docker-compose docs - ulimits](https://docs.docker.com/compose/compose-file/compose-file-v3/#ulimits)

**Comment by HervePruvost** [comment]
Hi @StWiemann,
changing the `ulimit` values for `n`, resp. open files, solved the problem.
Thx a lot.

P.S.: I have another problem but I open another issue for that.

**Comment by StWiemann** [comment]
Great, then I am closing this issue.
