### ISSUE TITLE
Container name is already in use

### ISSUE THREAD

**Issue by RAWA97** [N5GEH/n5geh.platform#5]
Hi there,

I have already went through the tutorial of fiware and now I want to initialize the platform on the same Linux system.
Everything went fine until I have to run the command docker compose up -d.
I always get the error message: "Error response from daemon: Conflict. The container name "/mongo-db" is already in use by container "3ba0331802c6fd19fec1ef2650111e7cfa45db0bff489fa4f8f59c7a5745c37a". You have to remove (or rename) that container to be able to reuse that name."

The problem is that "docker ps" says that there are no container running.

![2022-12-05 11_02_04-172 20 33 2_22 (Standard zoc) walterra@VMP-N5GEH_ _LVM_Tutorial_n5geh platform](https://user-images.githubusercontent.com/119852285/205609338-216420ec-90ce-40b4-a1dd-2628a61b36cc.png)

**Comment by djs0109** [comment]
Hi, with `docker ps -a` you can get a list of all containers, no matter they are currently active or not. I can imagine that, there are a deactivated "mongo-db" on your machine, which caused this conflict. You can remove all the stopped containers with `docker container prune`, and then try to start our platform again.

**Comment by RAWA97** [comment]
thanks, that was the problem.
The platform is running now :)

**Comment by RAWA97** [comment]
thanks, that was the problem.
The platform is running now :)
