### ISSUE TITLE
Migrate to docker compose v2

### ISSUE THREAD

**Issue by tstorek** [N5GEH/n5geh.platform#8]
As docker-compose v1 does not receiver any updates anymore.
I would recommend to migrate to docker compose v2.

This would come along with some addtional useful features.

However, some commands would change in the tutorial, e.g.:

```
docker-compose up -d --env-file=.env
```
would become
```
docker compose --env-file .env up -d
```

**Comment by djs0109** [comment]
That's true, I will put the `docker-compose` only as an extra notice for `V1`.
